name: AhuVista

services:
  server:
    image: dandychux/ahuvista-server
    container_name: ahuvista-server
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - '8000:8000'
    volumes:
      - logs:/var/log/ahuvista
    environment:
      APP_ENV: prod
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  postgresDB:
  logs: